ALTER TABLE users
    CHANGE `name` `first_name` VARCHAR(20) NOT NULL,
    ADD COLUMN `middle_name` VARCHAR(20) NULL AFTER `first_name`,
    ADD COLUMN `last_name` VARCHAR(20) NOT NULL,
    ADD COLUMN `email` VARCHAR(180) NOT NULL,
    ADD COLUMN `phone` VARCHAR(15) NOT NULL,
    ADD COLUMN `username` VARCHAR(10) NOT NULL,
    ADD COLUMN `password` VARCHAR(255) NOT NULL,
    ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP