CREATE TABLE posts (
    id INT(5) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_id INT(5) NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT not NULL,
    image VARCHAR(255),
    trashed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY(user_id) REFERENCES users(id)
);